using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "e96c74586afb826a")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Contact</summary>
	[PublishedContentModel("contact")]
	public partial class Contact : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contact";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Contact(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Contact, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Pages</summary>
	[PublishedContentModel("page")]
	public partial class Page : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "page";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Page(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Page, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// List Page: This contains all pages of your website
		///</summary>
		[ImplementPropertyType("listPage")]
		public object ListPage
		{
			get { return this.GetPropertyValue("listPage"); }
		}
	}

	/// <summary>Slider Item</summary>
	[PublishedContentModel("sliderItem")]
	public partial class SliderItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sliderItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SliderItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SliderItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// First-line text
		///</summary>
		[ImplementPropertyType("firstLineText")]
		public string FirstLineText
		{
			get { return this.GetPropertyValue<string>("firstLineText"); }
		}

		///<summary>
		/// Short Description
		///</summary>
		[ImplementPropertyType("shortDescription")]
		public string ShortDescription
		{
			get { return this.GetPropertyValue<string>("shortDescription"); }
		}

		///<summary>
		/// Slider Image
		///</summary>
		[ImplementPropertyType("sliderImage")]
		public IPublishedContent SliderImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("sliderImage"); }
		}

		///<summary>
		/// Slider Title
		///</summary>
		[ImplementPropertyType("sliderTitle")]
		public string SliderTitle
		{
			get { return this.GetPropertyValue<string>("sliderTitle"); }
		}

		///<summary>
		/// Slider Url
		///</summary>
		[ImplementPropertyType("sliderUrl")]
		public IPublishedContent SliderUrl
		{
			get { return this.GetPropertyValue<IPublishedContent>("sliderUrl"); }
		}
	}

	/// <summary>Sliders</summary>
	[PublishedContentModel("sliders")]
	public partial class Sliders : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sliders";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Sliders(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Sliders, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Blogs</summary>
	[PublishedContentModel("blogs")]
	public partial class Blogs : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "blogs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Blogs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Blogs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Blog Item</summary>
	[PublishedContentModel("blogItem")]
	public partial class BlogItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "blogItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlogItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Blog Url
		///</summary>
		[ImplementPropertyType("blogUrl")]
		public IPublishedContent BlogUrl
		{
			get { return this.GetPropertyValue<IPublishedContent>("blogUrl"); }
		}

		///<summary>
		/// Category
		///</summary>
		[ImplementPropertyType("category")]
		public IEnumerable<IPublishedContent> Category
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("category"); }
		}

		///<summary>
		/// Content: Add your blog content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return this.GetPropertyValue<IHtmlString>("content"); }
		}

		///<summary>
		/// Short Description: Add your short description to show in thumbnail
		///</summary>
		[ImplementPropertyType("shortDescription")]
		public string ShortDescription
		{
			get { return this.GetPropertyValue<string>("shortDescription"); }
		}

		///<summary>
		/// Tags
		///</summary>
		[ImplementPropertyType("tags")]
		public IEnumerable<string> Tags
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("tags"); }
		}

		///<summary>
		/// Thumbnail: Add your blog thumbnail
		///</summary>
		[ImplementPropertyType("thumbnail")]
		public IPublishedContent Thumbnail
		{
			get { return this.GetPropertyValue<IPublishedContent>("thumbnail"); }
		}

		///<summary>
		/// Title: Name your blog
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	// Mixin content Type 1089 with alias "header"
	/// <summary>Header</summary>
	public partial interface IHeader : IPublishedContent
	{
		/// <summary>Logo Image</summary>
		IPublishedContent LogoImage { get; }

		/// <summary>Logo Text</summary>
		string LogoText { get; }

		/// <summary>Logo Url</summary>
		IPublishedContent LogoUrl { get; }

		/// <summary>Navbar</summary>
		IEnumerable<IPublishedContent> Navbar { get; }

		/// <summary>Social Medias</summary>
		IEnumerable<IPublishedContent> SocialMedias { get; }
	}

	/// <summary>Header</summary>
	[PublishedContentModel("header")]
	public partial class Header : PublishedContentModel, IHeader
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "header";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Header(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Header, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Logo Image
		///</summary>
		[ImplementPropertyType("logoImage")]
		public IPublishedContent LogoImage
		{
			get { return GetLogoImage(this); }
		}

		/// <summary>Static getter for Logo Image</summary>
		public static IPublishedContent GetLogoImage(IHeader that) { return that.GetPropertyValue<IPublishedContent>("logoImage"); }

		///<summary>
		/// Logo Text
		///</summary>
		[ImplementPropertyType("logoText")]
		public string LogoText
		{
			get { return GetLogoText(this); }
		}

		/// <summary>Static getter for Logo Text</summary>
		public static string GetLogoText(IHeader that) { return that.GetPropertyValue<string>("logoText"); }

		///<summary>
		/// Logo Url
		///</summary>
		[ImplementPropertyType("logoUrl")]
		public IPublishedContent LogoUrl
		{
			get { return GetLogoUrl(this); }
		}

		/// <summary>Static getter for Logo Url</summary>
		public static IPublishedContent GetLogoUrl(IHeader that) { return that.GetPropertyValue<IPublishedContent>("logoUrl"); }

		///<summary>
		/// Navbar
		///</summary>
		[ImplementPropertyType("navbar")]
		public IEnumerable<IPublishedContent> Navbar
		{
			get { return GetNavbar(this); }
		}

		/// <summary>Static getter for Navbar</summary>
		public static IEnumerable<IPublishedContent> GetNavbar(IHeader that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("navbar"); }

		///<summary>
		/// Social Medias
		///</summary>
		[ImplementPropertyType("socialMedias")]
		public IEnumerable<IPublishedContent> SocialMedias
		{
			get { return GetSocialMedias(this); }
		}

		/// <summary>Static getter for Social Medias</summary>
		public static IEnumerable<IPublishedContent> GetSocialMedias(IHeader that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("socialMedias"); }
	}

	// Mixin content Type 1091 with alias "footer"
	/// <summary>Footer</summary>
	public partial interface IFooter : IPublishedContent
	{
		/// <summary>Footer Content</summary>
		string FooterContent { get; }
	}

	/// <summary>Footer</summary>
	[PublishedContentModel("footer")]
	public partial class Footer : PublishedContentModel, IFooter
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "footer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Footer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Footer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer Content
		///</summary>
		[ImplementPropertyType("footerContent")]
		public string FooterContent
		{
			get { return GetFooterContent(this); }
		}

		/// <summary>Static getter for Footer Content</summary>
		public static string GetFooterContent(IFooter that) { return that.GetPropertyValue<string>("footerContent"); }
	}

	/// <summary>Social Media Item</summary>
	[PublishedContentModel("socialMedia")]
	public partial class SocialMedia : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "socialMedia";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SocialMedia(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SocialMedia, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Platform Icon
		///</summary>
		[ImplementPropertyType("platformIcon")]
		public IHtmlString PlatformIcon
		{
			get { return this.GetPropertyValue<IHtmlString>("platformIcon"); }
		}

		///<summary>
		/// Platform Name
		///</summary>
		[ImplementPropertyType("platformName")]
		public string PlatformName
		{
			get { return this.GetPropertyValue<string>("platformName"); }
		}

		///<summary>
		/// Platform Url
		///</summary>
		[ImplementPropertyType("platformUrl")]
		public string PlatformUrl
		{
			get { return this.GetPropertyValue<string>("platformUrl"); }
		}
	}

	/// <summary>Navbar Item</summary>
	[PublishedContentModel("navbarItem")]
	public partial class NavbarItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "navbarItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NavbarItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NavbarItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Navbar Item Icon
		///</summary>
		[ImplementPropertyType("navbarItemIcon")]
		public IHtmlString NavbarItemIcon
		{
			get { return this.GetPropertyValue<IHtmlString>("navbarItemIcon"); }
		}

		///<summary>
		/// Navbar Item Name
		///</summary>
		[ImplementPropertyType("navbarItemName")]
		public string NavbarItemName
		{
			get { return this.GetPropertyValue<string>("navbarItemName"); }
		}

		///<summary>
		/// Navbar Url
		///</summary>
		[ImplementPropertyType("navbarUrl")]
		public IPublishedContent NavbarUrl
		{
			get { return this.GetPropertyValue<IPublishedContent>("navbarUrl"); }
		}
	}

	// Mixin content Type 1099 with alias "newsletterItem"
	/// <summary>Newsletter Item</summary>
	public partial interface INewsletterItem : IPublishedContent
	{
		/// <summary>Subtext</summary>
		string Subtext { get; }

		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>Newsletter Item</summary>
	[PublishedContentModel("newsletterItem")]
	public partial class NewsletterItem : PublishedContentModel, INewsletterItem
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "newsletterItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NewsletterItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NewsletterItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Subtext
		///</summary>
		[ImplementPropertyType("subtext")]
		public string Subtext
		{
			get { return GetSubtext(this); }
		}

		/// <summary>Static getter for Subtext</summary>
		public static string GetSubtext(INewsletterItem that) { return that.GetPropertyValue<string>("subtext"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(INewsletterItem that) { return that.GetPropertyValue<string>("title"); }
	}

	/// <summary>Blog Category Item</summary>
	[PublishedContentModel("blogCategoryItem")]
	public partial class BlogCategoryItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "blogCategoryItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlogCategoryItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogCategoryItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Category Name: Your category name
		///</summary>
		[ImplementPropertyType("categoryName")]
		public string CategoryName
		{
			get { return this.GetPropertyValue<string>("categoryName"); }
		}

		///<summary>
		/// Category Slug: Your category slug
		///</summary>
		[ImplementPropertyType("categorySlug")]
		public string CategorySlug
		{
			get { return this.GetPropertyValue<string>("categorySlug"); }
		}
	}

	/// <summary>Blog Categories</summary>
	[PublishedContentModel("blogCategories")]
	public partial class BlogCategories : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "blogCategories";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlogCategories(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogCategories, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Template Setting</summary>
	[PublishedContentModel("templateSetting")]
	public partial class TemplateSetting : PublishedContentModel, IFooter, IHeader, INewsletterItem
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "templateSetting";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TemplateSetting(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TemplateSetting, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer Content
		///</summary>
		[ImplementPropertyType("footerContent")]
		public string FooterContent
		{
			get { return Umbraco.Web.PublishedContentModels.Footer.GetFooterContent(this); }
		}

		///<summary>
		/// Logo Image
		///</summary>
		[ImplementPropertyType("logoImage")]
		public IPublishedContent LogoImage
		{
			get { return Umbraco.Web.PublishedContentModels.Header.GetLogoImage(this); }
		}

		///<summary>
		/// Logo Text
		///</summary>
		[ImplementPropertyType("logoText")]
		public string LogoText
		{
			get { return Umbraco.Web.PublishedContentModels.Header.GetLogoText(this); }
		}

		///<summary>
		/// Logo Url
		///</summary>
		[ImplementPropertyType("logoUrl")]
		public IPublishedContent LogoUrl
		{
			get { return Umbraco.Web.PublishedContentModels.Header.GetLogoUrl(this); }
		}

		///<summary>
		/// Navbar
		///</summary>
		[ImplementPropertyType("navbar")]
		public IEnumerable<IPublishedContent> Navbar
		{
			get { return Umbraco.Web.PublishedContentModels.Header.GetNavbar(this); }
		}

		///<summary>
		/// Social Medias
		///</summary>
		[ImplementPropertyType("socialMedias")]
		public IEnumerable<IPublishedContent> SocialMedias
		{
			get { return Umbraco.Web.PublishedContentModels.Header.GetSocialMedias(this); }
		}

		///<summary>
		/// Subtext
		///</summary>
		[ImplementPropertyType("subtext")]
		public string Subtext
		{
			get { return Umbraco.Web.PublishedContentModels.NewsletterItem.GetSubtext(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.NewsletterItem.GetTitle(this); }
		}
	}

	/// <summary>Contact Form</summary>
	[PublishedContentModel("contactForm")]
	public partial class ContactForm : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactForm";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactForm(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactForm, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// First Name
		///</summary>
		[ImplementPropertyType("firstName")]
		public string FirstName
		{
			get { return this.GetPropertyValue<string>("firstName"); }
		}

		///<summary>
		/// Last Name
		///</summary>
		[ImplementPropertyType("lastName")]
		public string LastName
		{
			get { return this.GetPropertyValue<string>("lastName"); }
		}

		///<summary>
		/// Message
		///</summary>
		[ImplementPropertyType("message")]
		public string Message
		{
			get { return this.GetPropertyValue<string>("message"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public int Phone
		{
			get { return this.GetPropertyValue<int>("phone"); }
		}

		///<summary>
		/// Reply
		///</summary>
		[ImplementPropertyType("reply")]
		public IHtmlString Reply
		{
			get { return this.GetPropertyValue<IHtmlString>("reply"); }
		}

		///<summary>
		/// Status
		///</summary>
		[ImplementPropertyType("status")]
		public string Status
		{
			get { return this.GetPropertyValue<string>("status"); }
		}
	}

	/// <summary>Products</summary>
	[PublishedContentModel("product")]
	public partial class Product : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "product";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Product(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Product, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Product Item</summary>
	[PublishedContentModel("productItem")]
	public partial class ProductItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "productItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProductItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProductItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Detail Description
		///</summary>
		[ImplementPropertyType("detailDescription")]
		public IHtmlString DetailDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("detailDescription"); }
		}

		///<summary>
		/// Discount Percent
		///</summary>
		[ImplementPropertyType("discountPercent")]
		public int DiscountPercent
		{
			get { return this.GetPropertyValue<int>("discountPercent"); }
		}

		///<summary>
		/// Discount Price
		///</summary>
		[ImplementPropertyType("discountPrice")]
		public int DiscountPrice
		{
			get { return this.GetPropertyValue<int>("discountPrice"); }
		}

		///<summary>
		/// Image Collection
		///</summary>
		[ImplementPropertyType("imageCollection")]
		public IEnumerable<IPublishedContent> ImageCollection
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("imageCollection"); }
		}

		///<summary>
		/// Price
		///</summary>
		[ImplementPropertyType("price")]
		public int Price
		{
			get { return this.GetPropertyValue<int>("price"); }
		}

		///<summary>
		/// Product Categories
		///</summary>
		[ImplementPropertyType("productCategories")]
		public IEnumerable<IPublishedContent> ProductCategories
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("productCategories"); }
		}

		///<summary>
		/// Product Name
		///</summary>
		[ImplementPropertyType("productName")]
		public string ProductName
		{
			get { return this.GetPropertyValue<string>("productName"); }
		}

		///<summary>
		/// Quantity
		///</summary>
		[ImplementPropertyType("quantity")]
		public int Quantity
		{
			get { return this.GetPropertyValue<int>("quantity"); }
		}

		///<summary>
		/// Short Description
		///</summary>
		[ImplementPropertyType("shortDescription")]
		public string ShortDescription
		{
			get { return this.GetPropertyValue<string>("shortDescription"); }
		}

		///<summary>
		/// Thumbnail
		///</summary>
		[ImplementPropertyType("thumbnail")]
		public IPublishedContent Thumbnail
		{
			get { return this.GetPropertyValue<IPublishedContent>("thumbnail"); }
		}
	}

	/// <summary>Product Category Item</summary>
	[PublishedContentModel("productCategoryItem")]
	public partial class ProductCategoryItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "productCategoryItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProductCategoryItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProductCategoryItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Product Category Name
		///</summary>
		[ImplementPropertyType("productCategoryName")]
		public string ProductCategoryName
		{
			get { return this.GetPropertyValue<string>("productCategoryName"); }
		}
	}

	/// <summary>Product Categories</summary>
	[PublishedContentModel("productCategories")]
	public partial class ProductCategories : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "productCategories";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProductCategories(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProductCategories, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
